import type { Metadata } from "next";
import "./globals.css";
import { Inter } from 'next/font/google';
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const interFont = Inter({
  variable: "--font-inter",
  subsets: ['latin'],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es"
      className={`m-6 ${interFont.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />

        {children}
        
        <Footer />
      </body>
    </html>
  );
}
